version: '3.9'

services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - './public:/var/www/html'
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache/nginx
    networks:
      - internal
  iconsbank_php:
    build:
      dockerfile: php-Dockerfile
      context: .
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - './public:/var/www/html'
    networks:
      - internal

networks:
  internal:
    driver: bridge
