version: '3.2'

networks:
  backend_network:

services:
  server:
    build: 
      context: ./server
    restart: always
    networks: 
      - backend_network
  client:
    depends_on:
      - server
    build: 
      context: ./client
    restart: always
    networks: 
      - backend_network
  surreptitious:
    networks: 
      - backend_network
    build: 
      context: ./surreptitious
    ports:
      - "2222:22"
    restart: always
    cap_add:
      - NET_RAW
      - NET_ADMIN
